# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: PDB tests with IBM DB2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2.1.0
      with:
        java-version: 8
        distribution: zulu

    - name: Cache Maven packages
      uses: actions/cache@v2.1.6
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Test with IBM DB2
      run: mvn -B clean test -Pdb2

  test-jdk11:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 11
          distribution: zulu

      - name: Cache Maven packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-jdk11
          restore-keys: ${{ runner.os }}-m2-jdk11

      - name: Test with IBM DB2
        run: mvn -B clean test -Pdb2

  test-jdk17:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 17
          distribution: zulu

      - name: Cache Maven packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-jdk17
          restore-keys: ${{ runner.os }}-m2-jdk17

      - name: Test with IBM DB2
        run: mvn -B clean test -Pdb2
